"""initial schema

Revision ID: 7b82ff03700a
Revises: 
Create Date: 2026-02-23 18:07:32.122877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b82ff03700a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('preferred_units', sa.String(length=20), nullable=False),
    sa.Column('default_servings', sa.Integer(), nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('smart_rule', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_owner_id'), 'collections', ['owner_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_attribution', sa.String(length=255), nullable=True),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('cook_time', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('base_servings', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_owner_id'), 'recipes', ['owner_id'], unique=False)
    op.create_table('collaborators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborators_collection_id'), 'collaborators', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collaborators_user_id'), 'collaborators', ['user_id'], unique=False)
    op.create_table('collection_recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_recipes_collection_id'), 'collection_recipes', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_recipes_recipe_id'), 'collection_recipes', ['recipe_id'], unique=False)
    op.create_table('cook_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cooked_at', sa.DateTime(), nullable=False),
    sa.Column('servings_made', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cook_logs_recipe_id'), 'cook_logs', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_cook_logs_user_id'), 'cook_logs', ['user_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_recipe_id'), 'equipment', ['recipe_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('group_label', sa.String(length=255), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_recipe_id'), 'ingredients', ['recipe_id'], unique=False)
    op.create_table('nutrition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('pairings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('section_label', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_recipe_id'), 'steps', ['recipe_id'], unique=False)
    op.create_table('voice_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cook_log_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cook_log_id'], ['cook_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notes_cook_log_id'), 'voice_notes', ['cook_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_notes_cook_log_id'), table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_index(op.f('ix_steps_recipe_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_table('pairings')
    op.drop_table('nutrition')
    op.drop_index(op.f('ix_ingredients_recipe_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_equipment_recipe_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_cook_logs_user_id'), table_name='cook_logs')
    op.drop_index(op.f('ix_cook_logs_recipe_id'), table_name='cook_logs')
    op.drop_table('cook_logs')
    op.drop_index(op.f('ix_collection_recipes_recipe_id'), table_name='collection_recipes')
    op.drop_index(op.f('ix_collection_recipes_collection_id'), table_name='collection_recipes')
    op.drop_table('collection_recipes')
    op.drop_index(op.f('ix_collaborators_user_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_collection_id'), table_name='collaborators')
    op.drop_table('collaborators')
    op.drop_index(op.f('ix_recipes_owner_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_collections_owner_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
