"""core data models

Revision ID: d697755a6dc5
Revises: 
Create Date: 2026-05-23 19:26:12.044292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd697755a6dc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'active', 'primacy', 'subordinate', 'drifting', 'released', 'completed', name='goalstate'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('weekly_time_hours', sa.Float(), nullable=True),
    sa.Column('weekly_tss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('memoir', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.Enum('hrv', 'sleep_score', 'sleep_duration_hours', 'resting_hr', 'body_battery', 'tss', 'weight', 'subjective_feel', 'alcohol_units', 'physical_state', 'illness_log', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('garmin', 'strava', 'manual', 'telegram', name='metricsource'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('ix_metric_readings_type_ts', 'metric_readings', ['metric_type', 'timestamp'], unique=False)
    op.execute("SELECT create_hypertable('metric_readings', 'timestamp', if_not_exists => TRUE)")
    op.create_table('resource_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('time_envelope_hours', sa.Float(), nullable=False),
    sa.Column('sleep_hours_per_night', sa.Float(), nullable=True),
    sa.Column('work_hours_per_week', sa.Float(), nullable=True),
    sa.Column('recovery_envelope_tss', sa.Float(), nullable=False),
    sa.Column('attention_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start', name='uq_resource_profiles_week_start')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'active', 'achieved', 'missed', name='milestonestate'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_goal_id'), 'milestones', ['goal_id'], unique=False)
    op.create_table('sacrifices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resource', sa.Enum('time', 'recovery', 'attention', 'willpower', name='resourcetype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sacrifices_goal_id'), 'sacrifices', ['goal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sacrifices_goal_id'), table_name='sacrifices')
    op.drop_table('sacrifices')
    op.drop_index(op.f('ix_milestones_goal_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_table('resource_profiles')
    op.drop_index('ix_metric_readings_type_ts', table_name='metric_readings')
    op.drop_table('metric_readings')
    op.drop_table('goals')
    sa.Enum(name='goalstate').drop(op.get_bind())
    sa.Enum(name='metrictype').drop(op.get_bind())
    sa.Enum(name='metricsource').drop(op.get_bind())
    sa.Enum(name='milestonestate').drop(op.get_bind())
    sa.Enum(name='resourcetype').drop(op.get_bind())
    # ### end Alembic commands ###
